services:
  db:
    image: postgres:16-alpine
    container_name: auth_postgres_db
    restart: always
    environment:
      POSTGRES_DB: django_auth
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d django_auth"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: auth_django_web
    restart: always
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
