services:
  db:
    image: postgres:16-alpine
    container_name: auth_postgres_db
    restart: always
    environment:
      POSTGRES_DB: django_auth
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d django_auth"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: auth_django_web
    restart: always
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-f#tjk5jd33!_)24pti7a%-1l0*nbmzoq*&#&4!2h5!6xgzm#t&
      - DATABASE_URL=postgres://auth_user:auth_password@db:5432/django_auth
      - GOOGLE_CLIENT_ID=908768559469-jav1ueeapdambje3kabp5t8cfmk56315.apps.googleusercontent.com
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=smtp.resend.com
      - EMAIL_PORT=465
      - EMAIL_USE_TLS=False
      - EMAIL_USE_SSL=True
      - EMAIL_HOST_USER=resend
      - EMAIL_HOST_PASSWORD=re_hYaojsga_FBuyZH2wcs7wkogpUdQvnUEo
      - DEFAULT_FROM_EMAIL=onboarding@resend.dev
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
