# Generated by Django 6.0.7 on 2026-07-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='role',
            field=models.CharField(choices=[('advertiser', 'Advertiser/Promoter'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
