# Generated by Django 6.0.7 on 2026-07-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otptoken_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='role',
        ),
    ]
